MerriweatherRegular.otf:
	curl 'https://fontlibrary.org/assets/fonts/merriweather/142672c6320f911143e31116582716be/202792c46e405324fd7777ba2a3345cc/MerriweatherRegular.otf' \
		--output MerriweatherRegular.otf

MerriweatherBold.otf:
	curl 'https://fontlibrary.org/assets/fonts/merriweather/142672c6320f911143e31116582716be/8a36e088006b7635fd015f04507e5580/MerriweatherBold.otf' \
		--output MerriweatherBold.otf

tachyons.min.css:
	curl 'https://unpkg.com/tachyons@4.6.1/css/tachyons.min.css' \
		--output tachyons.min.css

highlightjs.min.css:
	curl 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.1/styles/default.min.css' \
		--output highlightjs.min.css

highlightjs.min.js:
	curl 'https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.1/highlight.min.js' \
		--output highlightjs.min.js

all: MerriweatherRegular.otf MerriweatherBold.otf tachyons.min.css highlightjs.min.css highlightjs.min.js

.PHONY: all

