name: Deploy

on:
  push:
    branches:
      - source

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: JS deps
      run: npm ci
    - name: Build site
      run: |
        git fetch origin master:master
        git checkout master
        git merge source --no-commit
        npm run build
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add --all
        git commit -m "build: ${GITHUB_RUN_NUMBER}"
    - name: Deploy changes to master branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
